---
apiVersion: v1
kind: Namespace
metadata:
  name: algotrades

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: algotrades-api
  namespace: algotrades
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algotrades-api
      tier: algotrades
      track: stable
  template:
    metadata:
      labels:
        app: algotrades-api
        tier: algotrades
        track: stable
    spec:
      containers:
      - name: algotrades-api
        image: localhost:32000/algotrades-api:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        ports:
        - containerPort: 50001
        env:
          - name: PROVISIONER_NAME
            value: ksemin.in/nf
          - name: NFS_SERVER
            value: 192.168.0.101
          - name: NFS_PATH
            value: /
      volumes:
        - name: algotrades-api-data
          nfs:
            server: 192.168.0.101
            path: /data/apps/nbot/logs
---
apiVersion: v1
kind: Service
metadata:
  name: algotrades-api-service
  namespace: algotrades
spec:
  type: ClusterIP
  selector:
    app: algotrades-api
    tier: algotrades
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: algotrades-api-ingress
  namespace: algotrades
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: public
  tls:
  - hosts:
    - api.algotrades.web.ksemin.in
    secretName: api-algotrades-web-ksemin-in-tls
  rules:
    - host: api.algotrades.web.ksemin.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: algotrades-api-service
                port:
                  number: 5000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: algotrades-api-hpa
  namespace: algotrades
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: algotrades-api
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 90
